-- 10-Day Flow Supabase Schema Definition
-- Based on src/types/database.ts

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. user_profiles
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  avatar_url TEXT,
  password TEXT, -- Keeping as per type definition, though usually auth.users handles this
  ai_api_key TEXT,
  ai_service_provider TEXT,
  ai_prompts JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. dimensions
CREATE TABLE IF NOT EXISTS public.dimensions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  dimension_name TEXT NOT NULL,
  icon_name TEXT NOT NULL,
  color_code TEXT NOT NULL,
  display_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  ai_persona_prompt TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. cycles
CREATE TABLE IF NOT EXISTS public.cycles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_number INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  total_days INTEGER NOT NULL DEFAULT 10,
  completion_rate INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL CHECK (status IN ('pending', 'not_started', 'active', 'completed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, cycle_number)
);

-- 4. records
CREATE TABLE IF NOT EXISTS public.records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  dimension_id BIGINT NOT NULL REFERENCES public.dimensions(id) ON DELETE CASCADE,
  record_date DATE NOT NULL,
  content TEXT NOT NULL,
  word_count INTEGER NOT NULL DEFAULT 0,
  ai_suggestions TEXT,
  ai_quote TEXT,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft', 'published')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. record_attachments
CREATE TABLE IF NOT EXISTS public.record_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id BIGINT NOT NULL REFERENCES public.records(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  file_type TEXT NOT NULL CHECK (file_type IN ('image', 'audio')),
  file_url TEXT NOT NULL,
  file_name TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. expenses
CREATE TABLE IF NOT EXISTS public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_id BIGINT NOT NULL REFERENCES public.records(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  item_name TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  expense_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. reading_books
CREATE TABLE IF NOT EXISTS public.reading_books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  book_title TEXT NOT NULL,
  author TEXT,
  reading_status TEXT NOT NULL DEFAULT 'reading' CHECK (reading_status IN ('reading', 'completed', 'paused')),
  progress_percent INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. cycle_reports (Note: architecture review suggested merging/removing due to redundancy, keeping based on schema)
CREATE TABLE IF NOT EXISTS public.cycle_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  work_summary TEXT,
  reading_books TEXT,
  investment_summary TEXT,
  expense_summary TEXT,
  other_summary TEXT,
  suggestions TEXT,
  ai_generated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. milestones
CREATE TABLE IF NOT EXISTS public.milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  event_date DATE NOT NULL,
  event_title TEXT NOT NULL,
  event_description TEXT,
  event_type TEXT NOT NULL CHECK (event_type IN ('achievement', 'challenge', 'decision', 'other')),
  related_dimension_id BIGINT REFERENCES public.dimensions(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. cycle_goals
CREATE TABLE IF NOT EXISTS public.cycle_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  dimension_id BIGINT NOT NULL REFERENCES public.dimensions(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  evaluation_criteria TEXT NOT NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('quantitative', 'qualitative')),
  target_value NUMERIC(10, 2),
  target_unit TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. daily_goals
CREATE TABLE IF NOT EXISTS public.daily_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  goal_date DATE NOT NULL,
  dimension_id BIGINT NOT NULL REFERENCES public.dimensions(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  evaluation_criteria TEXT NOT NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('quantitative', 'qualitative')),
  target_value NUMERIC(10, 2),
  target_unit TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 12. goal_evaluations
CREATE TABLE IF NOT EXISTS public.goal_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  goal_id BIGINT NOT NULL,
  goal_type TEXT NOT NULL CHECK (goal_type IN ('cycle', 'daily')),
  dimension_id BIGINT NOT NULL REFERENCES public.dimensions(id) ON DELETE CASCADE,
  ai_score NUMERIC(5, 2) NOT NULL,
  ai_analysis TEXT NOT NULL,
  user_score NUMERIC(5, 2),
  user_comment TEXT,
  final_score NUMERIC(5, 2),
  evaluated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13. growth_tags
CREATE TABLE IF NOT EXISTS public.growth_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tag_name TEXT NOT NULL,
  frequency INTEGER NOT NULL DEFAULT 1,
  dimension_id BIGINT REFERENCES public.dimensions(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 14. knowledge_base
CREATE TABLE IF NOT EXISTS public.knowledge_base (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  dimension_id BIGINT NOT NULL REFERENCES public.dimensions(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  record_date DATE NOT NULL,
  content TEXT NOT NULL,
  media_urls TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 15. reports
CREATE TABLE IF NOT EXISTS public.reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cycle_id BIGINT NOT NULL REFERENCES public.cycles(id) ON DELETE CASCADE,
  dimension_id BIGINT REFERENCES public.dimensions(id) ON DELETE CASCADE,
  report_type TEXT NOT NULL CHECK (report_type IN ('cycle', 'monthly', 'dimension_overall')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- 16. 体重记录表 (weight_records)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.weight_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    weight_kg NUMERIC(5,2) NOT NULL,
    record_date DATE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Views

-- View: v_user_cycle_stats
CREATE OR REPLACE VIEW public.v_user_cycle_stats AS
SELECT 
    c.user_id,
    c.id AS cycle_id,
    c.cycle_number,
    COUNT(DISTINCT r.id) AS total_records,
    COALESCE(SUM(e.amount), 0) AS total_expense,
    c.completion_rate
FROM 
    public.cycles c
LEFT JOIN 
    public.records r ON c.id = r.cycle_id
LEFT JOIN 
    public.expenses e ON c.id = e.cycle_id
GROUP BY 
    c.id, c.user_id, c.cycle_number, c.completion_rate;

-- View: v_user_global_stats
CREATE OR REPLACE VIEW public.v_user_global_stats AS
WITH user_records_by_dim AS (
    SELECT 
        r.user_id,
        d.dimension_name,
        COUNT(r.id) as record_count
    FROM public.records r
    JOIN public.dimensions d ON r.dimension_id = d.id
    GROUP BY r.user_id, d.dimension_name
)
SELECT 
    c.user_id,
    COUNT(DISTINCT CASE WHEN c.status = 'completed' THEN c.id END) AS total_cycles_completed,
    COALESCE((SELECT COUNT(id) FROM public.records r WHERE r.user_id = c.user_id), 0) AS total_records,
    COALESCE((SELECT SUM(amount) FROM public.expenses e WHERE e.user_id = c.user_id), 0) AS total_expense,
    COALESCE(AVG(c.completion_rate), 0) AS avg_completion_rate,
    COALESCE(MAX(CASE WHEN urd.dimension_name = '工作' THEN urd.record_count END), 0) AS work_records,
    COALESCE(MAX(CASE WHEN urd.dimension_name = '阅读' THEN urd.record_count END), 0) AS reading_records,
    COALESCE(MAX(CASE WHEN urd.dimension_name = '投资' THEN urd.record_count END), 0) AS investment_records,
    COALESCE(MAX(CASE WHEN urd.dimension_name = '费用' THEN urd.record_count END), 0) AS expense_records,
    COALESCE(MAX(CASE WHEN urd.dimension_name NOT IN ('工作', '阅读', '投资', '费用') THEN urd.record_count END), 0) AS other_records
FROM 
    public.cycles c
LEFT JOIN 
    user_records_by_dim urd ON c.user_id = urd.user_id
GROUP BY 
    c.user_id;

-- Row Level Security (RLS) Enablement
-- Loop through all tables and enable RLS
DO $$ 
DECLARE 
  t text;
BEGIN
  FOR t IN 
    SELECT table_name FROM information_schema.tables 
    WHERE table_schema = 'public' 
      AND table_type = 'BASE TABLE'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
    
    -- Create default policy: Users can only see and modify their own rows
    -- Assumes all tables have a user_id column
    EXECUTE format('
      CREATE POLICY "Users can manage their own %I" 
      ON public.%I 
      FOR ALL USING (auth.uid() = user_id);
    ', t, t);
  END LOOP;
END $$;
