import React from 'react';
import type { LucideProps } from 'lucide-react';
import {
    Activity,
    BarChart2,
    Book,
    BookOpen,
    Brain,
    Briefcase,
    Calendar,
    CheckCircle2,
    CircleDot,
    Clock,
    Coffee,
    CreditCard,
    DollarSign,
    Dumbbell,
    Edit2,
    FileText,
    Flag,
    Flower2,
    GraduationCap,
    Heart,
    HeartPulse,
    History,
    Home,
    Landmark,
    Laptop,
    LayoutGrid,
    Lightbulb,
    Moon,
    PenSquare,
    Plane,
    Plus,
    Receipt,
    Settings,
    Star,
    Trash2,
    Trophy,
    Users,
    Utensils,
    Zap,
} from 'lucide-react';

const icons = {
    Activity,
    BarChart2,
    Book,
    BookOpen,
    Brain,
    Briefcase,
    Calendar,
    CheckCircle2,
    CircleDot,
    Clock,
    Coffee,
    CreditCard,
    DollarSign,
    Dumbbell,
    Edit2,
    FileText,
    Flag,
    Flower2,
    GraduationCap,
    Heart,
    HeartPulse,
    History,
    Home,
    Landmark,
    Laptop,
    LayoutGrid,
    Lightbulb,
    Moon,
    PenSquare,
    Plane,
    Plus,
    Receipt,
    Settings,
    Star,
    Trash2,
    Trophy,
    Users,
    Utensils,
    Zap,
};

type IconName = keyof typeof icons;

export const iconMap: Record<string, IconName> = {
    work: 'Briefcase',
    auto_stories: 'BookOpen',
    account_balance: 'Landmark',
    payments: 'CreditCard',
    health_and_safety: 'HeartPulse',
    directions_run: 'Activity',
    restaurant: 'Utensils',
    nightlight: 'Moon',
    emoji_events: 'Trophy',
    psychology: 'Brain',
    edit: 'Edit2',
    add: 'Plus',
    delete: 'Trash2',
    settings: 'Settings',
    home: 'Home',
    flag: 'Flag',
    history: 'History',
    description: 'FileText',
    receipt: 'Receipt',
    attach_money: 'DollarSign',
    laptop_mac: 'Laptop',
    school: 'GraduationCap',
    menu_book: 'Book',
    fitness_center: 'Dumbbell',
    self_improvement: 'Flower2',
    local_cafe: 'Coffee',
    flight_takeoff: 'Plane',
    diversity_3: 'Users',
    favorite: 'Heart',
    star: 'Star',
    bolt: 'Zap',
    lightbulb: 'Lightbulb',
    check_circle: 'CheckCircle2',
    schedule: 'Clock',
    event: 'Calendar',
    // Fallbacks
    grid_view: 'LayoutGrid',
    edit_square: 'PenSquare',
    bar_chart: 'BarChart2',
};

interface DynamicIconProps extends Omit<LucideProps, 'color'> {
    name: string;
    color?: string;
    className?: string;
}

export default function DynamicIcon({ name, ...props }: DynamicIconProps) {
    const lucideName = iconMap[name] || 'CircleDot';
    const Icon = icons[lucideName] || CircleDot;
    return <Icon {...props} />;
}
